<a href="https://colab.research.google.com/github/RiddyMazumder/Zero-to-Pandas/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 2 - Numpy Array Operations**
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
>
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions.

- function 1
- function 2
- function 3
- function 4
- function 5

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 1.8 MB/s eta 0:00:00


In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [33]:
# List of functions explained
function1 = np.concatenate  # (change this)
function2 = np.reshape
function3 = np.mean
function4 = np.std
function5 = np.dot

## Function 1 - np.concatenate (change this)

Add some explanation about the function in your own words

In [5]:
# Example 1 - working (change this)
arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6, 7],
        [8, 9, 10]]

np.concatenate((arr1, arr2), axis=1)

# For concatenation axis=1,arr1 and arr2 have 2 rows, so they can be concatenated.


array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

Explanation about example

In [16]:
# Example 2 - working
arr1 = [[1, 2, 3]]

arr2 = [[5, 6, 7]]


np.concatenate((arr1 , arr2), axis=0)
#arr1 and arr2 have the same number of columns 3, they can be concatenated at axis=0.

array([[1, 2, 3],
       [5, 6, 7]])

Explanation about example

In [31]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6, 7], [8, 9, 10]])
r = np.concatenate((arr1, arr2), axis=0)


#all the input arrays must have same number of dimensions

#to fix this we have to arr1 to Match arr2

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 3

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [32]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - ???

Add some explanations

In [50]:
# Example 1 - working
A= np.array([[1,2,3,5]])
r=np.reshape(A,(2,2))
print(r)


#  some explanations
#np.reshape to change the shape of arr from a 1D array to a 2D array with shape(2,2)

[[1 2]
 [3 5]]


Explanation about example

In [47]:
# Example 2 - working
A= np.array([[1, 2, 3], [4, 5, 6]])

# Reshape it to a 3D array with shape (2, 1, 3)
r = np.reshape(A, (2, 1, 3))
print(r)


#arr to a 3D array with shape (2, 1, 3).that's 2 blocks, alos 1 row and 3 columns.

[[[1 2 3]]

 [[4 5 6]]]


Explanation about example

In [53]:
# Example 3 - breaking (to illustrate when it breaks)
A= np.array([1, 2, 3, 4, 5, 6])

r = np.reshape(A, (4, -1))
r

#original array is 6, it cannot be reshaped into a shape of (4, -1),, also no integer that can multiply with 4 to yield 6.

ValueError: cannot reshape array of size 6 into shape (4,newaxis)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [54]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - ???

Add some explanations

In [58]:
# Example 1 - working
A = np.array([[1, 2, 3],
                  [4, 5, 6]])
B = np.mean(A)
print("Mean:", B)
a = np.mean(A, axis=0)
print("Mean axis 0:", a)
b = np.mean(A, axis=1)
print("Mean axis 1:", b)
#first column: ((1 + 4) / 2 = 2.5)
#second column: ((2 + 5) / 2 = 3.5)
#third column: ((3 + 6) / 2 = 4.5)
#When axis=1:
# first row: ((1 + 2 + 3) / 3 = 2.0)
#second row: ((4 + 5 + 6) / 3 = 5.0)

Mean: 3.5
Mean axis 0: [2.5 3.5 4.5]
Mean axis 1: [2. 5.]


Explanation about example

In [59]:
# Example 2 - working
A = np.array([[[1, 2], [3, 4]],
                  [[5, 6], [7, 8]]])
r= np.mean(A)
print("Mean):", r)

r1 = np.mean(A, axis=0)
print("Mean axis 0):")
print(r1)
r2 = np.mean(A, axis=1)
print("Mean axis 1):")
print(r2)

r3 = np.mean(A, axis=2)
print("Mean axis 2):")
print(r3)


Mean): 4.5
Mean axis 0):
[[3. 4.]
 [5. 6.]]
Mean axis 1):
[[2. 3.]
 [6. 7.]]
Mean axis 2):
[[1.5 3.5]
 [5.5 7.5]]


Explanation about example

In [66]:
# Example 3 - breaking (to illustrate when it breaks)
A = np.array([1, 2, np.nan, 4, 5])

B= np.mean(A)
print("Mean :", B)
c = np.nanmean(A)
print("Mean of array ignoring NaN :", c)

#to fix
#use np.nanmean to compute the mean while ignoring those NaN values or(( remove or fill NaN values))



Mean : nan
Mean of array ignoring : 3.0


Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [67]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - ???

Add some explanations

In [72]:
# Example 1 - working
A = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

R0 = np.std(A, axis=0)
print("Standard Deviation at axis 0 (columns):", R0)


R1 = np.std(A, axis=1)
print("Standard Deviation at axis 1 (rows):", R1)
#standard deviation for each column(axis=0)
#standard deviation for each row(axis=1)

Standard Deviation at axis 0 (columns): [2.44948974 2.44948974 2.44948974]
Standard Deviation at axis 1 (rows): [0.81649658 0.81649658 0.81649658]


Explanation about example

In [73]:
# Example 2 - working

R3 = np.std(A, axis=0, ddof=1)
print("Sample Standard Deviation at axis 0 (columns):", R3)
#ddof parameter using (N-1) as the divisor


Sample Standard Deviation at axis 0 (columns): [3. 3. 3.]


Explanation about example

In [77]:
# Example 3 - breaking (to illustrate when it breaks)
A= np.array([1, 2, 'three', 4])
r= np.std(A)
print("Standard Deviation of array:", r)

#Remove Non-Numeric Elements or Convert Elements to Numeric


SyntaxError: invalid syntax (<ipython-input-77-c8c5cf0ca7a9>, line 5)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [83]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - ???

Add some explanations

In [79]:
# Example 1 - working
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
result = np.dot(a, b)
result

array([[19, 22],
       [43, 50]])

Explanation about example

In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]])
c= np.array([1, 2, 3])
result = function5(a, c)
result

array([14, 32])

Explanation about example

In [82]:
# Example 3 - breaking (to illustrate when it breaks)
a = np.array([[1, 2], [3, 4], [5, 6]])
c = np.array([1, 2, 3])
result = function5(a, c)
result
#matrix_d has 2 columns, while vector_d has 3 elements=====Why It Breaks
#Reshape the Matrix (a) or Change the Shape of the Vector (b)

ValueError: shapes (3,2) and (3,) not aligned: 2 (dim 1) != 3 (dim 0)

Explanation about example (why it breaks and how to fix it)

Some closing comments about when to use this function.

In [84]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [85]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
